server:
  port: 10000
  servlet:
    context-path: /authority

spring:
  main:
    allow-bean-definition-overriding: true
  mvc:
    throw-exception-if-no-handler-found: true

oauth2:
  secret: YXBpYXBwOkI1OmhSJ05eNSlKS04/RWo=