seata:
  enabled: true
  tx-service-group: apn_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: public
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
      data-id: apn_tx_group.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      namespace: public
      group: DEFAULT_GROUP
      username: nacos
      password: nacos