spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: staging
    sentinel:
      transport:
        dashboard: localhost:8088
        port: 8720
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: data-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

feign:
  sentinel:
    enabled: true

seata:
  enabled: true
  tx-service-group: apn_tx_group
  enable-auto-data-source-proxy: true
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: staging
      group: DEFAULT_GROUP
      username: nacos
      password: nacos
      data-id: apn_tx_group.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      namespace: staging
      group: DEFAULT_GROUP
      username: nacos
      password: nacos

management:
  endpoints:
    web:
      exposure:
        include: '*'
