server:
  port: 9003

spring:
  application:
    name: job-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8720
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true