server:
  port: 8888
  servlet:
    context-path: /

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: job-routh
          uri: lb://job-service
          predicates:
            - Path=/job/**
            #- After=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]
            #- Cookie=chocolate, ch.p
            #- Header=X-Request-Id, \d+
            #- Host=**.somehost.org,**.anotherhost.org
            #- Method=GET,POST
            #- Query=green
            #- RemoteAddr=192.168.1.1/24
            #- Weight=group1, 2
        - id: company-routh
          uri: lb://company-service
          predicates:
            - Path=/company/**
        - id: talent-routh
          uri: lb://talent-service
          predicates:
            - Path=/talent/**
        - id: authority-routh
          uri: lb://authority-service
          predicates:
            - Path=/authority/**
        - id: admin-routh
          uri: lb://admin-service
          predicates:
            - Path=/admin/**