spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        username: nacos
        password: nacos
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
    sentinel:
      transport:
        dashboard: localhost:8090
        port: 8720
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            username: ${spring.cloud.nacos.config.username}
            password: ${spring.cloud.nacos.config.password}
            namespace: ${namespace:dev}
            groupId: SENTINEL_GROUP
            dataId: sentinel-${spring.application.name}-flow-rules
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            username: ${spring.cloud.nacos.config.username}
            password: ${spring.cloud.nacos.config.password}
            namespace: ${namespace:dev}
            groupId: SENTINEL_GROUP
            dataId: sentinel-${spring.application.name}-degrade-rules
            rule-type: degrade
        param-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            username: ${spring.cloud.nacos.config.username}
            password: ${spring.cloud.nacos.config.password}
            namespace: ${namespace:dev}
            groupId: SENTINEL_GROUP
            dataId: sentinel-${spring.application.name}-param-flow-rules
            rule-type: param-flow
        system:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            username: ${spring.cloud.nacos.config.username}
            password: ${spring.cloud.nacos.config.password}
            namespace: ${namespace:dev}
            groupId: SENTINEL_GROUP
            dataId: sentinel-${spring.application.name}-system-rules
            rule-type: system
        authority:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            username: ${spring.cloud.nacos.config.username}
            password: ${spring.cloud.nacos.config.password}
            namespace: ${namespace:dev}
            groupId: SENTINEL_GROUP
            dataId: sentinel-${spring.application.name}-authority-rules
            rule-type: authority

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000