spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dev
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
    sentinel:
      transport:
        dashboard: localhost:8090
        port: 8720
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: data-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 600000